# docker-compose.yml
version: "3"
services:
  backend:
    build: backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - api_nw
      - api_db
  
  front-end:
    build: ./frontend
    ports:
      - 80:80
    networks:
      - api_nw
      
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - api_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      
networks:
  api_nw:
    driver: bridge
  api_db:
    driver: bridge