# docker-compose.yml
version: "3"
services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - api_nw
      - api_db

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - api_db
    volumes:
      - ./postgres-data/data/:/var/lib/postgresql/data
      - ./postgres-data/sql/:/docker-entrypoint-initdb.d
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    user: 'root'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - api_db


networks:
  api_nw:
    driver: bridge
  api_db:
    driver: bridge